@startuml
class com.formdev.flatlaf.fonts.roboto.FlatRobotoFont
class com.formdev.flatlaf.themes.FlatMacLightLaf
class com.motorph.gui.Banner
class com.motorph.gui.EmployeeFrame
class com.motorph.gui.FinanceFrame
class com.motorph.gui.HRFrame
class com.motorph.gui.LoginFrame
class controllers.EmployeeController
class form.AddEmployeeForm
class form.EditEmployeeForm
class form.EditPayrollForm
class java.awt.BorderLayout
class java.awt.Font
class java.awt.Window
class java.awt.event.ActionEvent
class java.sql.Connection
class java.sql.DriverManager
class java.sql.PreparedStatement
class java.sql.ResultSet
class java.sql.SQLException
class java.text.NumberFormat
class java.time.Month
class java.util.Calendar
class javax.swing.ImageIcon
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.JOptionPane
class javax.swing.JPanel
class javax.swing.JScrollPane
class javax.swing.JTable
class javax.swing.SwingUtilities
class javax.swing.UIManager
class javax.swing.UnsupportedLookAndFeelException
class javax.swing.table.DefaultTableModel
class main.PayrollSystem
class model.Employee
class org.mindrot.jbcrypt.BCrypt
class service.AuthService
class service.DBConnection
class service.PasswordUtil
@enduml